### ISSUE TITLE
Mix.Project.deps_paths/0 not found deploying with edeliver

### ISSUE THREAD

**Issue by vinceurag** [ateliware/triplex#45]
Any idea on how to deploy this with edeliver? Whenever I ran `mix edeliver migrate staging` it does not run the tenant migrations.

Any help would be greatly appreciated.

Thanks!

**Comment by vinceurag** [comment]
I encounter this error in production:

```
04:28:40.898 [error] #PID<0.1554.0> running MyAppWeb.Endpoint terminated
Server: testproduction.com:80 (http)
Request: POST /v2/companies/
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Mix.Project.deps_paths/0 is undefined (module Mix.Project is not available)
        Mix.Project.deps_paths()
        (triplex) lib/triplex.ex:268: Triplex.source_repo_priv/1
        (triplex) lib/triplex.ex:226: Triplex.migrations_path/1
        (triplex) lib/triplex.ex:207: Triplex.migrate/2
        (triplex) lib/triplex.ex:106: Triplex.create_schema/3
        (my_app) lib/my_app/accounts/accounts.ex:71: MyApp.Accounts.create_company/1
        (my_app) lib/my_app_web/controllers/company_controller.ex:15: MyAppWeb.CompanyController.create/2
        (my_app) lib/my_app_web/controllers/company_controller.ex:1: MyAppWeb.CompanyController.action/2

**Comment by mgiacomini** [comment]
did you ran the command `mix triplex.migrate`? I think edeliver migrate command will executes only the /priv/repo/migrations.

**Comment by vinceurag** [comment]
How do i run it in production? I think Mix is not included when deployed to production.

Thanks.

**Comment by kelvinst** [comment]
@vinceurag we have also some other problems with OTP releases, like #41, I'll check all of them ASAP! Thanks for reporting!

**Comment by kelvinst** [comment]
@vinceurag, what is your triplex version? I suspect it's a very old version...

**Comment by vinceurag** [comment]
@kelvinst, thanks for replying! I believe it's the latest.
I have this in my mix.exs:
```
{:triplex, git: "https://github.com/ateliware/triplex.git"}
```

**Comment by vinceurag** [comment]
Any update on this, @kelvinst? :)

**Comment by kelvinst** [comment]
@vinceurag Sorry, I've got no time to look at it recently. You can check this post about running migrations on OTP releases: https://medium.com/nebo-15/runtime-configuration-migrations-and-deployment-for-elixir-applications-6295b892fa6a

**Comment by vinceurag** [comment]
PR #49 solves this 🏆

**Comment by kelvinst** [comment]
@vinceurag thanks for the feedback! :)

**Comment by symmetrically** [comment]
@kelvinst for some reason I am still getting this error. Here is the error when running the application in foreground using edeliver : 

```
INSERT INTO "customers" ("name","subdomain","inserted_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "id" ["Dev Company", "dev-company", {{2018, 6, 15}, {11, 53, 40, 496542}}, {{2018, 6, 15}, {11, 53, 40, 496557}}]
[debug] QUERY OK db=4.7ms queue=0.2ms
CREATE SCHEMA "dev-company" []
[info] Sent 500 in 30ms
[error] #PID<0.1768.0> running AppWeb.Endpoint (cowboy_protocol) terminated
Server: myediteddomain.com:80 (http)
Request: POST /create_step_two
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Mix.Project.deps_paths/0 is undefined (module Mix.Project is not available)
        Mix.Project.deps_paths()
        (ecto) lib/mix/ecto.ex:172: Mix.Ecto.source_repo_priv/1
        (triplex) lib/triplex.ex:188: Triplex.migrations_path/1
        (triplex) lib/triplex.ex:172: Triplex.migrate/2
        (app) lib/app_web/controllers/workspace_controller.ex:62: appWeb.WorkspaceController.create_step_two/2
        (app) lib/app_web/controllers/workspace_controller.ex:1: appWeb.WorkspaceController.action/2
        (app) lib/app_web/controllers/workspace_controller.ex:1: appWeb.WorkspaceController.phoenix_controller_pipeline/2
        (app) lib/app_web/endpoint.ex:1: appWeb.Endpoint.instrument/4
```
