### ISSUE TITLE
Failing to Fetch and Insert into Tenant table

### ISSUE THREAD

**Issue by blisscs** [ateliware/triplex#55]
Hi, 

I am currently new and just started to use triplex library. I am having an issues that I can not fetch and insert into tenant tables. Please have a look in a log below, this log is generated from an phoenix app, to see more about this issue -

````
[debug] QUERY ERROR source="departments" db=2.8ms
SELECT d0."id", d0."name", d0."description", d0."inserted_at", d0."updated_at" FROM "awesome"."departments" AS d0 []
** (Postgrex.Error) ERROR 42P01 (undefined_table): relation "awesome.departments" does not exist
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
````

and as you can see the table is already been created with `Triplex.create/1` in the psql dialog below -
````
dev=# select * from 
awesome.             companies            hello.               information_schema.  pg_catalog.          pg_temp_1.           pg_toast.            pg_toast_temp_1.     public.              schema_migrations    
dev=# select * from awesome.
awesome.deparments         awesome.schema_migrations  
dev=# select * from awesome.deparments 
dev-# ;
 id | name | description | inserted_at | updated_at 
----+------+-------------+-------------+------------
(0 rows)

dev=# select * from awesome.schema_migrations ;
    version     |        inserted_at         
----------------+----------------------------
 20180405100559 | 2018-04-11 00:17:15.038774
(1 row)
````

I am using version 1.2.0 from hexpm and I am putting %{prefix: Triplex.to_prefix(tenant)} as the third parameter for both Repo.insert and other Repo's functions.
I was wondering are there anyways I can debug this to see what is the source of this issue?

**Comment by blisscs** [comment]
Please ignore the issue here. 
It's my mistake that I make, in my schema I use `deparments` but in migration I used `departments'.
That's why it is causing the issue.
